services:
  api:
    container_name: habit_test_api
    environment: 
      - PGUSER=habitapp
      - PGHOST=db
      - PGPASSWORD=habitapp_pass
      - PGDATABASE=habits
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: habit_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=habit_test
      - POSTGRES_PASSWORD=habitapp_pass
volumes:
  test_db:
networks: 
  default:
    name: debug_test
